//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace etest
{
    using System;
    using System.Collections.Generic;
    
    public partial class analysis
    {
        public int idanalysis { get; set; }
        public string cellitemID { get; set; }
        public string StudentID { get; set; }
        public string Answer { get; set; }
        public Nullable<int> Result { get; set; }
        public Nullable<int> tqID { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
