//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace etest
{
    using System;
    using System.Collections.Generic;
    
    public partial class cell_items
    {
        public cell_items()
        {
            this.item_keys = new HashSet<item_keys>();
            this.item_log = new HashSet<item_log>();
            this.tq_items = new HashSet<tq_items>();
        }
    
        public int CellItemID { get; set; }
        public Nullable<int> CellCaseID { get; set; }
        public string BloomsClass { get; set; }
        public string Item { get; set; }
        public string OptionA { get; set; }
        public string OptionB { get; set; }
        public string OptionC { get; set; }
        public string OptionD { get; set; }
        public string Status { get; set; }
        public string DifficultIndex { get; set; }
        public string DiscriminationIndex { get; set; }
        public Nullable<int> AuthoredBy_UserID { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    
        public virtual cell_cases cell_cases { get; set; }
        public virtual user user { get; set; }
        public virtual ICollection<item_keys> item_keys { get; set; }
        public virtual ICollection<item_log> item_log { get; set; }
        public virtual ICollection<tq_items> tq_items { get; set; }
    }
}
