//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace etest
{
    using System;
    using System.Collections.Generic;
    
    public partial class cell_cases
    {
        public cell_cases()
        {
            this.case_log = new HashSet<case_log>();
            this.cell_items = new HashSet<cell_items>();
            this.tq_cases = new HashSet<tq_cases>();
        }
    
        public int CellCaseID { get; set; }
        public Nullable<int> CurriculumID { get; set; }
        public Nullable<int> SyllabusID { get; set; }
        public string Case { get; set; }
        public Nullable<int> AuthoredBy_UserID { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string ApprovalStatus { get; set; }
    
        public virtual ICollection<case_log> case_log { get; set; }
        public virtual user user { get; set; }
        public virtual curriculum curriculum { get; set; }
        public virtual syllabu syllabu { get; set; }
        public virtual ICollection<cell_items> cell_items { get; set; }
        public virtual ICollection<tq_cases> tq_cases { get; set; }
    }
}
