//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace etest
{
    using System;
    using System.Collections.Generic;
    
    public partial class curriculum
    {
        public curriculum()
        {
            this.cell_cases = new HashSet<cell_cases>();
            this.syllabus = new HashSet<syllabu>();
            this.team_teach = new HashSet<team_teach>();
            this.tq_coverage = new HashSet<tq_coverage>();
        }
    
        public int CurriculumID { get; set; }
        public string YearLevel { get; set; }
        public string Subject { get; set; }
        public string DescriptiveTitle { get; set; }
        public string NormCourseOffering { get; set; }
    
        public virtual ICollection<cell_cases> cell_cases { get; set; }
        public virtual ICollection<syllabu> syllabus { get; set; }
        public virtual ICollection<team_teach> team_teach { get; set; }
        public virtual ICollection<tq_coverage> tq_coverage { get; set; }
    }
}
