//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace etest
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ge_test_schemaEntities : DbContext
    {
        public ge_test_schemaEntities()
            : base("name=ge_test_schemaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<analysis> analyses { get; set; }
        public virtual DbSet<blossomclass> blossomclasses { get; set; }
        public virtual DbSet<case_log> case_log { get; set; }
        public virtual DbSet<cell_cases> cell_cases { get; set; }
        public virtual DbSet<cell_items> cell_items { get; set; }
        public virtual DbSet<curriculum> curricula { get; set; }
        public virtual DbSet<faculty> faculties { get; set; }
        public virtual DbSet<faculty_type> faculty_type { get; set; }
        public virtual DbSet<item_keys> item_keys { get; set; }
        public virtual DbSet<item_log> item_log { get; set; }
        public virtual DbSet<key_log_use> key_log_use { get; set; }
        public virtual DbSet<notification> notifications { get; set; }
        public virtual DbSet<semester> semesters { get; set; }
        public virtual DbSet<syllabu> syllabus { get; set; }
        public virtual DbSet<system_logs> system_logs { get; set; }
        public virtual DbSet<team_teach> team_teach { get; set; }
        public virtual DbSet<topic_coverage> topic_coverage { get; set; }
        public virtual DbSet<tq> tqs { get; set; }
        public virtual DbSet<tq_answer_key> tq_answer_key { get; set; }
        public virtual DbSet<tq_cases> tq_cases { get; set; }
        public virtual DbSet<tq_coverage> tq_coverage { get; set; }
        public virtual DbSet<tq_coverage_log> tq_coverage_log { get; set; }
        public virtual DbSet<tq_generate> tq_generate { get; set; }
        public virtual DbSet<tq_items> tq_items { get; set; }
        public virtual DbSet<tq_log> tq_log { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<year_level> year_level { get; set; }
    }
}
