//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace etest
{
    using System;
    using System.Collections.Generic;
    
    public partial class item_keys
    {
        public item_keys()
        {
            this.key_log_use = new HashSet<key_log_use>();
            this.tq_items = new HashSet<tq_items>();
        }
    
        public int ItemKeyID { get; set; }
        public Nullable<int> CellItemID { get; set; }
        public string Key { get; set; }
        public string Answer { get; set; }
    
        public virtual cell_items cell_items { get; set; }
        public virtual ICollection<key_log_use> key_log_use { get; set; }
        public virtual ICollection<tq_items> tq_items { get; set; }
    }
}
