//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace etest
{
    using System;
    using System.Collections.Generic;
    
    public partial class syllabu
    {
        public syllabu()
        {
            this.cell_cases = new HashSet<cell_cases>();
            this.topic_coverage = new HashSet<topic_coverage>();
        }
    
        public int SyllabusID { get; set; }
        public Nullable<int> CurriculumID { get; set; }
        public Nullable<short> TopicNo { get; set; }
        public string Topic { get; set; }
        public Nullable<double> EstimatedTime { get; set; }
    
        public virtual ICollection<cell_cases> cell_cases { get; set; }
        public virtual curriculum curriculum { get; set; }
        public virtual ICollection<topic_coverage> topic_coverage { get; set; }
    }
}
