//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace etest
{
    using System;
    using System.Collections.Generic;
    
    public partial class tq
    {
        public tq()
        {
            this.key_log_use = new HashSet<key_log_use>();
            this.tq_answer_key = new HashSet<tq_answer_key>();
            this.tq_cases = new HashSet<tq_cases>();
            this.tq_log = new HashSet<tq_log>();
        }
    
        public int TqID { get; set; }
        public Nullable<int> TqCoverageID { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<key_log_use> key_log_use { get; set; }
        public virtual tq_coverage tq_coverage { get; set; }
        public virtual ICollection<tq_answer_key> tq_answer_key { get; set; }
        public virtual ICollection<tq_cases> tq_cases { get; set; }
        public virtual ICollection<tq_log> tq_log { get; set; }
    }
}
