//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace etest
{
    using System;
    using System.Collections.Generic;
    
    public partial class tq_answer_key
    {
        public int TqAnswerKey { get; set; }
        public Nullable<int> TqID { get; set; }
        public Nullable<short> ItemNo { get; set; }
        public string Answer { get; set; }
    
        public virtual tq tq { get; set; }
    }
}
