//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace etest
{
    using System;
    using System.Collections.Generic;
    
    public partial class tq_cases
    {
        public tq_cases()
        {
            this.tq_items = new HashSet<tq_items>();
        }
    
        public int TqCaseID { get; set; }
        public Nullable<int> TqID { get; set; }
        public Nullable<int> CellCaseID { get; set; }
    
        public virtual cell_cases cell_cases { get; set; }
        public virtual tq tq { get; set; }
        public virtual ICollection<tq_items> tq_items { get; set; }
    }
}
