//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace etest
{
    using System;
    using System.Collections.Generic;
    
    public partial class tq_generate
    {
        public int idtq_generate { get; set; }
        public Nullable<int> SyllabusID { get; set; }
        public Nullable<int> Hours_Spent { get; set; }
        public string Proportion { get; set; }
        public string rememberU { get; set; }
        public string rememberA { get; set; }
        public string understandU { get; set; }
        public string understandA { get; set; }
        public string applyU { get; set; }
        public string applyA { get; set; }
        public string analyzeU { get; set; }
        public string analyzeA { get; set; }
        public string evaluateU { get; set; }
        public string evaluateA { get; set; }
        public string createU { get; set; }
        public string createA { get; set; }
        public string totalItems { get; set; }
    }
}
