//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace etest
{
    using System;
    using System.Collections.Generic;
    
    public partial class tq_items
    {
        public int TqItemID { get; set; }
        public Nullable<int> TqCaseID { get; set; }
        public Nullable<int> CellItemID { get; set; }
        public Nullable<int> ItemKeyID { get; set; }
    
        public virtual cell_items cell_items { get; set; }
        public virtual item_keys item_keys { get; set; }
        public virtual tq_cases tq_cases { get; set; }
    }
}
