//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace etest
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class user
    {
        public user()
        {
            this.case_log = new HashSet<case_log>();
            this.cell_cases = new HashSet<cell_cases>();
            this.cell_items = new HashSet<cell_items>();
            this.item_log = new HashSet<item_log>();
            this.notifications = new HashSet<notification>();
            this.system_logs = new HashSet<system_logs>();
            this.team_teach = new HashSet<team_teach>();
            this.tq_coverage_log = new HashSet<tq_coverage_log>();
            this.tq_log = new HashSet<tq_log>();
        }
    
        public int UserID { get; set; }
        public Nullable<int> FacultyID { get; set; }
        [Required(ErrorMessage="Please Provide Login Name", AllowEmptyStrings=false)]
        public string LoginName { get; set; }
        [Required(ErrorMessage="Please Provide Password", AllowEmptyStrings=false)]
        [DataType(System.ComponentModel.DataAnnotations.DataType.Password)]
        public string Password { get; set; }
        public string UserType { get; set; }
        public string Assignment { get; set; }
    
        public virtual ICollection<case_log> case_log { get; set; }
        public virtual ICollection<cell_cases> cell_cases { get; set; }
        public virtual ICollection<cell_items> cell_items { get; set; }
        public virtual faculty faculty { get; set; }
        public virtual ICollection<item_log> item_log { get; set; }
        public virtual ICollection<notification> notifications { get; set; }
        public virtual ICollection<system_logs> system_logs { get; set; }
        public virtual ICollection<team_teach> team_teach { get; set; }
        public virtual ICollection<tq_coverage_log> tq_coverage_log { get; set; }
        public virtual ICollection<tq_log> tq_log { get; set; }
    }
}
